/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edusys.ui;

import edusys.utils.Auth;
import edusys.utils.MsgBox;
import edusys.utils.XImage;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author lam
 */
public class EdusysJFrame extends javax.swing.JFrame {
    void init(){
        setSize(1000, 600);
        setIconImage(XImage.getAppIcon());
        setLocationRelativeTo(null);
        setTitle("HỆ THỐNG ĐÀO TẠO EDUSYS");
         new Timer(1000,new ActionListener(){
             SimpleDateFormat format = new SimpleDateFormat("hh/mm/ss a");
            @Override
            public void actionPerformed(ActionEvent e) {
                lblDongHo.setText(format.format(new Date()));
            }
            
        }).start();
         this.openWelcome();
        this.openLogin();
    }
    /**
     * Creates new form EdusysJFrame
     */
    public EdusysJFrame() {
        initComponents();
        init();
    }
    void openWelcome(){
        new ChaoJDialog(this, true).setVisible(true);
    }
    void openLogin(){
        new DangNhapJDialog(this, true).setVisible(true);
    }
    void openDoiMatKhau(){
        
       if(Auth.isLogin()){
            new DoiMatKhauJDialog(this,true).setVisible(true);
        }else{
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
         
    }
    void openChuyenDe(){
        
       if(Auth.isLogin()){
            new ChuyenDeJDialog(this,true).setVisible(true);
        }else{
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
         
    }
    void openNguoiHoc(){
        
       if(Auth.isLogin()){
            new NguoiHocJDialog(this,true).setVisible(true);
        }else{
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
         
    }
    void openKhoaHoc(){
        
       if(Auth.isLogin()){
            new KhoaHocJDialog(this,true).setVisible(true);
        }else{
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
         
    }
   
    void openNhanVien(){
        
       if(Auth.isLogin()){
            new NhanVienJDialog(this,true).setVisible(true);
        }else{
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
         
    }
    void dangXuat(){
        Auth.clear();
        openLogin();
        
    }
    void ketThuc(){
        if (MsgBox.confirm(this, "Bạn có muốn kết thúc việc?")) {
             System.exit(0);
        }
    }
    
    void openThongKe(int index){
        if(Auth.isLogin() ){
            if(index == 3 && !Auth.isManager()){
                
                MsgBox.alert(this, "Bạn không có quyền xem thông tin doanh thu!");
                return;
            }
           
            
          ThongKeJDialog tk =  new ThongKeJDialog(this,true);
          tk.selectTab(index);
          tk.setVisible(true);
           
        }else{
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnDangXuat = new javax.swing.JButton();
        btnKetThuc = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnChuyenDe = new javax.swing.JButton();
        btnNguoiHoc = new javax.swing.JButton();
        btnKhoaHoc = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnHuongDan = new javax.swing.JButton();
        pnlTrangThai = new javax.swing.JPanel();
        lblDongHo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNoiDung = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        MNuHeThong = new javax.swing.JMenu();
        MNiDangNhap = new javax.swing.JMenuItem();
        MNiDangXuat = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        MNiDoiMatKhau = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        MNiKetThuc = new javax.swing.JMenuItem();
        MnuQuanLy = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        MNiNguoiHoc = new javax.swing.JMenuItem();
        MNiChuyenDe = new javax.swing.JMenuItem();
        MNiKhoaHoc = new javax.swing.JMenuItem();
        MNiNhanVien = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mniNguoiHocTungNam = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mniBangDiemKhoa = new javax.swing.JMenuItem();
        mniDiemTungKhoa = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mniDoanhThu = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mniHuongDan = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mniGioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 204));

        jToolBar1.setBackground(new java.awt.Color(153, 255, 153));
        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setRollover(true);

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/Log out.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDangXuat);

        btnKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/Stop.png"))); // NOI18N
        btnKetThuc.setText("Kết thúc");
        btnKetThuc.setFocusable(false);
        btnKetThuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKetThuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKetThuc);
        jToolBar1.add(jSeparator1);

        btnChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/Lists.png"))); // NOI18N
        btnChuyenDe.setText("Chuyên đề");
        btnChuyenDe.setFocusable(false);
        btnChuyenDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChuyenDe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenDeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnChuyenDe);

        btnNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/Conference.png"))); // NOI18N
        btnNguoiHoc.setText("Người học");
        btnNguoiHoc.setFocusable(false);
        btnNguoiHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNguoiHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNguoiHocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNguoiHoc);

        btnKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/Certificate.png"))); // NOI18N
        btnKhoaHoc.setText("Khoá học");
        btnKhoaHoc.setFocusable(false);
        btnKhoaHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhoaHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaHocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKhoaHoc);
        jToolBar1.add(jSeparator2);

        btnHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/Globe.png"))); // NOI18N
        btnHuongDan.setText("Hướng dẫn");
        btnHuongDan.setFocusable(false);
        btnHuongDan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuongDan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnHuongDan);

        pnlTrangThai.setBackground(new java.awt.Color(153, 255, 153));
        pnlTrangThai.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/Alarm.png"))); // NOI18N
        lblDongHo.setText("00/00/00 AM");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/Info.png"))); // NOI18N
        jLabel2.setText("Hệ quản lý đào tạo");

        javax.swing.GroupLayout pnlTrangThaiLayout = new javax.swing.GroupLayout(pnlTrangThai);
        pnlTrangThai.setLayout(pnlTrangThaiLayout);
        pnlTrangThaiLayout.setHorizontalGroup(
            pnlTrangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTrangThaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDongHo)
                .addContainerGap())
        );
        pnlTrangThaiLayout.setVerticalGroup(
            pnlTrangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrangThaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTrangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDongHo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblNoiDung.setBackground(new java.awt.Color(255, 153, 51));
        lblNoiDung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoiDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/logo.png"))); // NOI18N
        lblNoiDung.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jMenuBar.setBackground(new java.awt.Color(0, 255, 0));

        MNuHeThong.setBackground(new java.awt.Color(153, 255, 153));
        MNuHeThong.setText("Hệ thống");

        MNiDangNhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MNiDangNhap.setBackground(new java.awt.Color(153, 255, 153));
        MNiDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/Key.png"))); // NOI18N
        MNiDangNhap.setText("Đăng nhập");
        MNuHeThong.add(MNiDangNhap);

        MNiDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MNiDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/Log out.png"))); // NOI18N
        MNiDangXuat.setText("Đăng xuất");
        MNiDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNiDangXuatActionPerformed(evt);
            }
        });
        MNuHeThong.add(MNiDangXuat);
        MNuHeThong.add(jSeparator4);

        MNiDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/Refresh.png"))); // NOI18N
        MNiDoiMatKhau.setText("Đổi mật khẩu");
        MNiDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNiDoiMatKhauActionPerformed(evt);
            }
        });
        MNuHeThong.add(MNiDoiMatKhau);
        MNuHeThong.add(jSeparator5);

        MNiKetThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        MNiKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/Stop.png"))); // NOI18N
        MNiKetThuc.setText("Kết thúc");
        MNiKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNiKetThucActionPerformed(evt);
            }
        });
        MNuHeThong.add(MNiKetThuc);

        jMenuBar.add(MNuHeThong);

        MnuQuanLy.setText("Quản lý");
        MnuQuanLy.add(jSeparator3);

        MNiNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/Conference.png"))); // NOI18N
        MNiNguoiHoc.setText("Người học");
        MNiNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNiNguoiHocActionPerformed(evt);
            }
        });
        MnuQuanLy.add(MNiNguoiHoc);

        MNiChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/Lists.png"))); // NOI18N
        MNiChuyenDe.setText("Chuyên đề");
        MNiChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNiChuyenDeActionPerformed(evt);
            }
        });
        MnuQuanLy.add(MNiChuyenDe);

        MNiKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/Certificate.png"))); // NOI18N
        MNiKhoaHoc.setText("Khoá học");
        MNiKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNiKhoaHocActionPerformed(evt);
            }
        });
        MnuQuanLy.add(MNiKhoaHoc);

        MNiNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/User group.png"))); // NOI18N
        MNiNhanVien.setText("Quản lý nhân viên");
        MNiNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNiNhanVienActionPerformed(evt);
            }
        });
        MnuQuanLy.add(MNiNhanVien);

        jMenuBar.add(MnuQuanLy);

        jMenu4.setText("Thống kê");

        mniNguoiHocTungNam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/Clien list.png"))); // NOI18N
        mniNguoiHocTungNam.setText("Người học từng năm");
        mniNguoiHocTungNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNguoiHocTungNamActionPerformed(evt);
            }
        });
        jMenu4.add(mniNguoiHocTungNam);
        jMenu4.add(jSeparator6);

        mniBangDiemKhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/Card file.png"))); // NOI18N
        mniBangDiemKhoa.setText("Bảng điểm khoá học");
        mniBangDiemKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBangDiemKhoaActionPerformed(evt);
            }
        });
        jMenu4.add(mniBangDiemKhoa);

        mniDiemTungKhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/Bar chart.png"))); // NOI18N
        mniDiemTungKhoa.setText("Điểm chuyên đề");
        mniDiemTungKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDiemTungKhoaActionPerformed(evt);
            }
        });
        jMenu4.add(mniDiemTungKhoa);
        jMenu4.add(jSeparator7);

        mniDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/Dollar.png"))); // NOI18N
        mniDoanhThu.setText("Doanh thu từng chuyên đề");
        mniDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoanhThuActionPerformed(evt);
            }
        });
        jMenu4.add(mniDoanhThu);

        jMenuBar.add(jMenu4);

        jMenu6.setText("Trợ giúp");

        mniHuongDan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mniHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/Globe.png"))); // NOI18N
        mniHuongDan.setText("Hướng dẫn sử dụng");
        jMenu6.add(mniHuongDan);
        jMenu6.add(jSeparator8);

        mniGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusys/icon/Brick house.png"))); // NOI18N
        mniGioiThieu.setText("Giới thiệu sản phẩm");
        jMenu6.add(mniGioiThieu);

        jMenuBar.add(jMenu6);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
            .addComponent(pnlTrangThai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblNoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucActionPerformed
        // btn thoat
                ketThuc();
    }//GEN-LAST:event_btnKetThucActionPerformed

    private void MNiChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNiChuyenDeActionPerformed
        // TODO add your handling code here:
        openChuyenDe();
    }//GEN-LAST:event_MNiChuyenDeActionPerformed

    private void MNiKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNiKetThucActionPerformed
        // btn kết thúc
       ketThuc();
    }//GEN-LAST:event_MNiKetThucActionPerformed

    private void MNiKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNiKhoaHocActionPerformed
        // TODO add your handling code here:
        openKhoaHoc();
    }//GEN-LAST:event_MNiKhoaHocActionPerformed

    private void mniDiemTungKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDiemTungKhoaActionPerformed
        // TODO add your handling code here:
        openThongKe(2);
        
    }//GEN-LAST:event_mniDiemTungKhoaActionPerformed

    private void MNiDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNiDoiMatKhauActionPerformed
        // TODO add your handling code here:
        openDoiMatKhau();
    }//GEN-LAST:event_MNiDoiMatKhauActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // btn dang xuat
        dangXuat();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void MNiDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNiDangXuatActionPerformed
        // TODO add your handling code here:
        dangXuat();
    }//GEN-LAST:event_MNiDangXuatActionPerformed

    private void btnChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenDeActionPerformed
        //btn chuyen de
      openChuyenDe();
    }//GEN-LAST:event_btnChuyenDeActionPerformed

    private void btnNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNguoiHocActionPerformed
        // btn nguoi hoc
        openNguoiHoc();
    }//GEN-LAST:event_btnNguoiHocActionPerformed

    private void btnKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaHocActionPerformed
        //btn kha hoc
        openKhoaHoc();
    }//GEN-LAST:event_btnKhoaHocActionPerformed

    private void MNiNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNiNhanVienActionPerformed
        // TODO add your handling code here:
        openNhanVien();
    }//GEN-LAST:event_MNiNhanVienActionPerformed

    private void MNiNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNiNguoiHocActionPerformed
        // TODO add your handling code here:
        openNguoiHoc();
    }//GEN-LAST:event_MNiNguoiHocActionPerformed

    private void mniNguoiHocTungNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNguoiHocTungNamActionPerformed
        // TODO add your handling code here:
        openThongKe(1);
    }//GEN-LAST:event_mniNguoiHocTungNamActionPerformed

    private void mniBangDiemKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBangDiemKhoaActionPerformed
        // TODO add your handling code here:
        openThongKe(0);
    }//GEN-LAST:event_mniBangDiemKhoaActionPerformed

    private void mniDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoanhThuActionPerformed
        // TODO add your handling code here:
        openThongKe(3);
    }//GEN-LAST:event_mniDoanhThuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EdusysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EdusysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EdusysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EdusysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EdusysJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MNiChuyenDe;
    private javax.swing.JMenuItem MNiDangNhap;
    private javax.swing.JMenuItem MNiDangXuat;
    private javax.swing.JMenuItem MNiDoiMatKhau;
    private javax.swing.JMenuItem MNiKetThuc;
    private javax.swing.JMenuItem MNiKhoaHoc;
    private javax.swing.JMenuItem MNiNguoiHoc;
    private javax.swing.JMenuItem MNiNhanVien;
    private javax.swing.JMenu MNuHeThong;
    private javax.swing.JMenu MnuQuanLy;
    private javax.swing.JButton btnChuyenDe;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHuongDan;
    private javax.swing.JButton btnKetThuc;
    private javax.swing.JButton btnKhoaHoc;
    private javax.swing.JButton btnNguoiHoc;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblNoiDung;
    private javax.swing.JMenuItem mniBangDiemKhoa;
    private javax.swing.JMenuItem mniDiemTungKhoa;
    private javax.swing.JMenuItem mniDoanhThu;
    private javax.swing.JMenuItem mniGioiThieu;
    private javax.swing.JMenuItem mniHuongDan;
    private javax.swing.JMenuItem mniNguoiHocTungNam;
    private javax.swing.JPanel pnlTrangThai;
    // End of variables declaration//GEN-END:variables
}
